const $=id=>document.getElementById(id), kinds=['CDC','DEL','HUEL','OPEL'];
const split=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
function profile(){let p={};['name','campus','current_semester','degree','dual_degree','degree_level','minor'].forEach(k=>p[k]=$(k).value);p.admission_year=+$('admission_year').value||null;p.current_registered_units=+$('current_registered_units').value||0;p.completed_courses=split($('completed_courses').value);p.current_courses=split($('current_courses').value);p.interests=split($('interests').value);p.requirement_totals={};p.requirement_completed={};kinds.forEach(k=>{p.requirement_totals[k]=+$(`total_${k}`).value||0;p.requirement_completed[k]=+$(`done_${k}`).value||0});return p}
function fill(p={}){Object.entries(p).forEach(([k,v])=>{if($(k)&&!Array.isArray(v)&&typeof v!=='object')$(k).value=v??''});['completed_courses','current_courses','interests'].forEach(k=>$(k).value=(p[k]||[]).join(', '));kinds.forEach(k=>{$(`total_${k}`).value=p.requirement_totals?.[k]||0;$(`done_${k}`).value=p.requirement_completed?.[k]||0})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function sourceLine(s){if(!s)return'No source location';const pages=s.pages?.join(', ')||s.pdf_page||'?';return `${escapeHtml(s.source_document||'source')} · page ${escapeHtml(pages)}${s.section?' · '+escapeHtml(s.section):''}`}
function card(r){const pills=[...r.eligibility,...r.matches].map(x=>`<span class="pill">${escapeHtml(x)}</span>`).join('<span class="separator"> · </span>');const review=r.manual_review.map(x=>`<span class="pill review">Verify: ${escapeHtml(x)}</span>`).join('');const sections=r.sections.length?r.sections.map(s=>`${s.section}: ${s.meeting||'time unparsed'}${s.room?' · '+s.room:''}`).join('<br>'):'No reliably parsed section time';const evidence=r.evidence.map(e=>`<div class="evidence-row"><b>${escapeHtml(e.claim)}</b><span>${sourceLine(e.source)}</span></div>`).join('');return `<article class="course"><span class="code">${escapeHtml(r.course_code)} · CC ${r.computer_code}${r.requirement?' · '+r.requirement:''}</span><h3>${escapeHtml(r.title)}</h3><div class="pills">${pills}${review}</div><p><b>${r.units??'?'} units</b><br>${sections}</p><details><summary>Claim evidence (${r.evidence.length})</summary><div class="evidence">${evidence}</div></details><p class="source">${sourceLine(r.source)}${r.handout?.source_file?' · '+escapeHtml(r.handout.source_file):''}</p></article>`}
async function run(e){e?.preventDefault();const query=$('query').value.trim();if(!query)return;$('queryForm').classList.add('loading');try{const res=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:profile(),query})});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');$('analysis').classList.remove('hidden');$('analysis').innerHTML=`<div class="section-head"><div><span class="step">03</span><h2>Academic analysis</h2></div><b>${data.eligible_candidates} matched</b></div><div class="analysis-grid">${kinds.map(k=>`<div class="metric"><b>${data.remaining_requirements[k]}</b><span>${k} REMAINING</span></div>`).join('')}</div>${data.agent.warning?`<p class="notice">${escapeHtml(data.agent.warning)}</p>`:''}`;$('results').innerHTML=data.recommendations.length?data.recommendations.map(card).join(''):`<div class="empty"><h3>No matching courses</h3><p>The category or requested preferences could not be verified for this profile.</p></div>`}catch(err){$('results').innerHTML=`<div class="empty"><h3>Request failed</h3><p>${escapeHtml(err.message)}</p></div>`}finally{$('queryForm').classList.remove('loading')}}
kinds.forEach(k=>$('reqInputs').insertAdjacentHTML('beforeend',`<div class="req-row"><b>${k}</b><label>Total<input id="total_${k}" type="number" min="0" value="0"></label><label>Completed<input id="done_${k}" type="number" min="0" value="0"></label></div>`));
$('queryForm').addEventListener('submit',run);document.querySelectorAll('.examples button').forEach(b=>b.onclick=()=>{$('query').value=b.textContent;run()});$('save').onclick=async()=>{await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile())});$('save').textContent='Saved ✓';setTimeout(()=>$('save').textContent='Save profile',1300)};
Promise.all([fetch('/api/stats').then(r=>r.json()),fetch('/api/profile').then(r=>r.json())]).then(([s,p])=>{$('term').textContent=`${s.term||'Current term'} · ${s.current_offerings} offerings` ;fill(p)});
